import { ErrorBoundary } from '@/components/error-boundary';
import { LayoutProvider } from '@/components/layout-context';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const pretendard = localFont({
  src: '../assets/fonts/PretendardVariable.woff2',
  variable: '--font-pretendard',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Wit',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="ko">
      <head>
        <link
          rel="preconnect"
          href="https://cdn.jsdelivr.net"
          crossOrigin="anonymous"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/leetaewook/gmarket-sans-dynamic-subset/GmarketSans.css"
          crossOrigin="anonymous"
        />
      </head>
      <body className={`${pretendard.variable} antialiased`}>
        <LayoutProvider>
          <ErrorBoundary>{children}</ErrorBoundary>
        </LayoutProvider>
      </body>
    </html>
  );
};

export default RootLayout;
